# Default values for data-generator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  sidecar:
    repository: docker-virtual.artifactory.com/push-to-rt
    tag: 0.1
  main:
    repository: docker-virtual.artifactory.com/data-generator
    tag: 0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

generator:
  limit: 25
  repo: stable
  createList: false

imagePullSecrets:
  key: rt-docker-reg-key
  registry: docker-virtual.artifactory.com
  username: admin
  password: password

artifactory:
  install: false
  url: https://artifactory:8081/artifactory
  user: admin
  password: password
  threads: 20
  repoPath: helm-test-local/

initContainerImage: alpine

persistence:
    enabled: true
    mountPath: "/var/opt/helm-data-generator/"
    accessMode: ReadWriteOnce
    size: 10Gi

