apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: helm-binary-generator
  name: helm-binary-generator
spec:
  replicas: 1
  selector:
    app: helm-binary-generator
    deploymentconfig: helm-binary-generator
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: helm-binary-generator
        deploymentconfig: helm-binary-generator
    spec:
      containers:
        - args:
            - '-l=1000'
            - '-t=20'
            - '-r=stable'
            - '-rp=helm-stage'
            - '-u=admin'
            - >-
              -p=password
            - >-
              -rt=http://artifactory:8081/artifactory
          image: >-
            helm-binary-generator:0.1
          imagePullPolicy: IfNotPresent
          name: helm-binary-generator
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: rt-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange

